version: '3.6'
services:
    nginx:
        build: app/docker/nginx
        ports:
            - '8082:80'
        volumes:
            - './app:/usr/share/nginx/html'
    php:
        build: app/docker/php
        volumes:
            - './app:/usr/share/nginx/html'
    adminer:
        image: 'adminer:4.7'
        ports:
            - '8083:8080'
    composer:
        image: 'composer:1.8'
        command: install
        volumes:
            - './app:/app'
    db:
        image: 'postgres:10.4'
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=db
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=pwd
    node:
        build: app/docker/node
        ports:
            - '3000:3000'
        volumes:
            - './app:/home/node/app'
