vich_uploader:
    db_driver: orm

    mappings:
       property_picture:
            uri_prefix:         '%app.path.property_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.property_images%'